# Generated by Django 5.0.5 on 2024-06-02 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site1', '0002_stuff_delete_uploadedfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stuff',
            old_name='addess',
            new_name='address',
        ),
    ]
